version: 2.1

defaults: &defaults
  docker:
    - image: computesoftware/adoptopenjdk-11:intel-mkl-2018.4-057-tools-deps-1.10.1.496

orbs:
  cache: compute/cache@0.0.3

jobs:
  test:
    <<: *defaults

    steps:
      - checkout
      - run: clojure -J-Xmx3500m -A:test:test-runner

workflows:
  version: 2
  ci-workflow:
    jobs:
      - test