version: 2.1

defaults: &defaults
  docker:
    - image: computesoftware/java-neanderthal:a2c9cb308bb0f5f63746d89c1185b1522e6197b0-tools-deps

orbs:
  cache: compute/cache@0.0.3

jobs:
  test:
    <<: *defaults

    steps:
      - checkout
      - run: clojure -J-Xmx3500m -A:test:test-runner

workflows:
  version: 2
  ci-workflow:
    jobs:
      - test