version: 2.1

defaults: &defaults
  docker:
    - image: computesoftware/zulu-openjdk-11:dev-utils-intel-mkl-2018.4-057-tools-deps-1.11.1.1105-b2287c8

orbs:
  cache: compute/cache@0.0.3

jobs:
  test:
    <<: *defaults

    steps:
      - checkout
      - run:
          name: Run tests
          command: clojure -J-Xmx3500m -M:test:test-runner --reporter kaocha.report/documentation --plugin profiling

workflows:
  version: 2
  ci-workflow:
    jobs:
      - test
